branch-defaults:
  master:
    environment: sn7257TrueDatYoutub-production
global:
  application_name: sn_7257_true_dat_youtube
  branch: null
  default_ec2_keyname: signal_noise
  default_platform: Python 3.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
